[package]
name = "libfilewatcher"
version = "0.0.1"
authors = ["feenk gmbh <contact@feenk.com>"]
edition = "2021"

[dependencies]
notify = "4.0.12"
value-box = "1.1"
string-box = "1.1"
env_logger = "0.8"

[lib]
name = "filewatcher"
crate-type = ["cdylib"]
